export { HomePageSlider } from './Slider';
export { ProductCard } from './ProductCard';
export { HomePage } from './HomePage';
export { RegisterForm } from './ReduxForm';
export { AllWatch } from './AllWatch';
export { OriginWatch } from './OriginWatch';
export { NikeWatch } from './NikeWatch';
export { HermesWatch } from './HermesWatch';
export { EditionWatch } from './EditionWatch';
export { Watch } from './Watch';
export { ProductsList } from './ProductsList';
export {Cart} from './Cart';
export {EmptyCart} from './EmptyCart';
export {FullCart} from './FullCart';
export {UserCabinet} from './UserCabinet';
export {ChangeUserInfoPage, ChangeUserPasswordPage} from './UserCabinet/ChangeAccountInfo';